### PR TITLE
Social

### PR DESCRIPTION
**Pull request by imathis**
Integrated Octopress social. Fixed lots of template issues.

### CODE REVIEW

**Comment by imathis** [comment]
Here's a nice demo showing the default sharing options.

screenshot of safari 3-25-15 10 51 15 pm

Each of these are styled links which trigger a share action on the different social networks. A user can switch to the fancy javascript buttons by setting their theme config like this:

```yaml
share_with: buttons # (default: links)
```

Social links and buttons can be configured in the main _config.yml according to the [octopress-social](https://github.com/octopress/social) documentation.

**Comment by imathis** [comment]
Sharing buttons look like this.
screenshot of safari 3-25-15 11 46 35 pm

**Comment by mdotasia** [comment]
This is so cool!

**Comment by jilljenn** [comment]
Thanks. Those buttons are beautiful, I plan to isolate the code somewhere.

**Pull request merged**
